### ISSUE TITLE
node-gyp fails on node 12.5.0; node-gyp 5.0.3

### ISSUE THREAD

**Issue by rikvermeer** [fridgerator/PyNode#15]
Hii, I wanna try your library, it seems interesting. However I got this error when building.

../src/main.cpp:308:61: error: too few arguments to function call, single argument 'context' was not specified
      Nan::New<v8::FunctionTemplate>(OpenFile)->GetFunction());
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/rikvermeer/Library/Caches/node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(

**Comment by fridgerator** [comment]
I havent tested on node 12, looks like the node api changed.  I'll have to look into it.

Node 10.16.3 is working.

**Comment by fridgerator** [comment]
@rikvermeer Should be working in node 12 now :+1:

**Comment by rikvermeer** [comment]
Will try!! Thanks :D

I came here through this article btw:
https://thecodinginterface.com/blog/bridging-nodejs-and-python-with-pynode/

Maybe mention there that it works for node 12 now too?

**Comment by rikvermeer** [comment]
I made a venv I'm getting::

node index.js
`
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0x100078e78 node::Abort() [/usr/local/bin/node]
 2: 0x1000794f6 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10016a6bc v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: 0x103d90575 call(Nan::FunctionCallbackInfo<v8::Value> const&) [/Users/rikvermeer/workspace/testpynode/node_modules/@fridgerator/pynode/build/Release/PyNode.node]
 5: 0x103d92439 Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/rikvermeer/workspace/testpynode/node_modules/@fridgerator/pynode/build/Release/PyNode.node]
 6: 0x1001ccc58 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 7: 0x1001cc322 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 8: 0x1001cbb0a v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 9: 0x10071a3b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
[1]    80065 abort      node index.js
`

cat index.js
`
const pynode = require('@fridgerator/pynode');
pynode.startInterpreter();
pynode.appendSysPath('/');
pynode.openFile('test');
let x = pynode.call('add', 1, 2);
//console.log('x: ' + x);
`

cat test.py                                                                                                                                                                                                                  
`
def add(a, b):
  return a + b
`

**Comment by rikvermeer** [comment]
I've tested but got an error. I've filed it under:

https://github.com/fridgerator/PyNode/issues/17
