### ISSUE TITLE
New Version / Package?

### ISSUE THREAD

**Issue by tilor** [fridgerator/PyNode#39]
I'm using PyNode on Windows and Linux. On Linux I get installation problems with v0.4.6, on Windows v0.5.1 does not install...

There already seems to be a fix for binding.gyp in the code that addresses the lines that fail for me on Windows.

So how about a new version for npm?

P.S.: Besides that PyNode works like a charm for me, thanks a lot!

**Comment by fridgerator** [comment]
@tilor I can try to get a new version out this week.  Thanks for the kind words!

**Comment by fridgerator** [comment]
@tilor  hopefully this resolves your issue https://github.com/fridgerator/PyNode/commit/99abd9621f4bd0663f7ca106c21a34292e8bf2ba, version 0.5.2

**Comment by tilor** [comment]
@fridgerator Perfect - your solution works for my, I can now install version 0.5.2 on Windows and Mac! Thanks a lot!
